### ISSUE TITLE
Support for Industry Endpoints

### ISSUE THREAD

**Issue by joral** [Celeo/rfesi#1]
Adding support for the System list and Facilities list from the Industry endpoitn

**Comment by Celeo** [comment]
Sure, those endpoints sound like great additions. I see you have a commit for it on your fork, so feel free to open a PR when you're ready!

**Comment by joral** [comment]
> Sure, those endpoints sound like great additions. I see you have a commit for it on your fork, so feel free to open a PR when you're ready!

I'm working through all of the industry endpoints, so I wasn't sure if I should submit one pull for all, or multiple pulls as I complete and test each call.

**Comment by Celeo** [comment]
That's up to you - whichever is easier.

**Comment by Celeo** [comment]
Closing this, but feel free to comment back if you want to visit this again.
