### ISSUE TITLE
using group_character().get_public_info() raise an Exception on Reqwest

### ISSUE THREAD

**Issue by rafaga** [Celeo/rfesi#11]
Trying to run rfesi I'm getting 'Error constructing HTTP client' from using `esi.group_character().get_public_info(player.id).await?;`. What Can I do because I'm authenticating and using other functions like `esi.group_character().get_portrait(player.id).await?;`without any problems:

https://github.com/rafaga/webb/blob/0b93d62b8f94326633d1b7fc405b0b56b49b25bb/src/esi.rs#LL206C10-L206C10

```
   #[tokio::main]
   pub async fn auth_user(&mut self,port: u16) -> Result<Option<Character>, Box<dyn std::error::Error + Send + Sync>> {
        [...]
        let claims = self.esi.authenticate(result.0.as_str()).await?;      

        let mut player = Character::new();  
        let data = claims.unwrap();
        player.name = data.name;
        let split:Vec<&str> = data.sub.split(":").collect();
        player.id = split[2].parse::<u64>().unwrap();
        if player.auth != None {
            [...]
            //IF I OMIT THIS LINE AN EXCEPTION ARISE
            self.esi.update_spec().await?;
            
            //THIS LINE RAISE THE EXCEPTION  'Error constructing HTTP client'
            let public_info = self.esi.group_character().get_public_info(player.id).await?;
            [...]

            //THIS LINE RUNS FINE
            let player_portraits = self.esi.group_character().get_portrait(player.id).await?;
            player.photo = Some(player_portraits.px64x64);
        }
        Ok(Some(player))
    }
```

I can't determine why there is an error here. please help me if you are not so busy.

```
running 1 test
2023-05-29 20:15:12.338628-0600 database-98a788513e93f095[34694:460942] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=34694
2023-05-29 20:15:12.339286-0600 database-98a788513e93f095[34694:460942] SecTaskCopyDebugDescription: database-98a7885[34694]/0#-1 LF=0
thread 'tests_database::test_add_character' panicked at 'An error occurred has ocurred: Error constructing HTTP client', tests/database.rs:90:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: database::tests_database::test_add_character
             at ./tests/database.rs:90:25
   3: database::tests_database::test_add_character::{{closure}}
             at ./tests/database.rs:65:29
   4: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests_database::test_add_character ... FAILED

failures:

failures:
    tests_database::test_add_character

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 28.51s
```

**Comment by Celeo** [comment]
Hi!

I'm not exactly sure. There seemed to be a problem with how I was determining access token expiration; I _think_ I've fixed that in version `0.16.0` if you want to try that?

**Comment by rafaga** [comment]
I have updated and tested in 0.16.0, but no success , if you want to test my library, you can clone my repo an run the `fn test_esi_get_public_data()` to get the error. I Edited the issue to reflect clearly where is the problem

**Comment by Celeo** [comment]
I see the same failure as you do, so at least we've got that going for us!

**Comment by Celeo** [comment]
I've got a fix for this in `0.16.1` - there's a field that CCP changed in the character public info endpoint. Let me know if this fixes it.

**Comment by rafaga** [comment]
updated and I can confirm that it's fixed for `group_character().get_public_info()`.

but using `group_corporation().get_public_info()` its raising a similar exception 

 `Failed to serialize/deserialize JSON; this may be due to unexpected data or invalid struct field(s)`. Do you like to open another issue or continue in this thread

**Comment by Celeo** [comment]
Good catch, sorry about that! I've gone through and updated all the structs that are in the library in `0.17.0`.

**Comment by rafaga** [comment]
Everything is Fixed thank you very much for your time.

**Comment by Celeo** [comment]
Great! Thanks for reporting.
