### ISSUE TITLE
JWT invalid token when authenticating new players

### ISSUE THREAD

**Issue by rafaga** [Celeo/rfesi#14]
like I was mentioning on #13 I can't add any new users using ESI because audience field in the claims aren't validating.

I want to know if you can reproduce the problem, how to do it:

* Authenticate a new user into ESI using this crate.

Throws an error "JWT audience field is incorrect" on v0.19.0. Such field comes with None value.

**Comment by Celeo** [comment]
For now, you can include the crate in your project with `rfesi = { version = "0.19.0", default-features = false, features = [] }` to turn off that feature.

**Comment by rafaga** [comment]
Investigating further the line 72 `validate(token, &validation_key, validations)?; ` validates without errors but the returned object comes empty. Any ideas on what its going on ?

https://github.com/Celeo/rfesi/blob/bba27b00d70ea4356588d0d2a0e5e002b92fe872/src/jwt_util.rs#L67-L97

**Comment by Celeo** [comment]
I pushed some updates; sorry fort the delay! Give `0.21.0` a try.

**Comment by rafaga** [comment]
its solved Thank you very much

**Comment by Celeo** [comment]
Happy to help! Thanks for reporting and your patience.
