### ISSUE TITLE
authenticate() throws FailedJsonParse(Error("missing field `scp`", line: 0, column: 0))

### ISSUE THREAD

**Issue by Borkido** [Celeo/rfesi#16]
When no scopes are requested the returned jwt from the Esi does not contain the scp field and serde throws an error when its decoded.

**Comment by Borkido** [comment]
If only one scope is specified it fails too: `FailedJsonParse(Error("invalid type: string \"esi-location.read_location.v1\", expected a sequence", line: 0, column: 0))`. Multiple scopes however do work. I was unable to confirm this earlier since i was unable to log into the 3rd party developer site at the time.

**Comment by Celeo** [comment]
Whoops, sorry! Give version `0.22.0` a try.

**Comment by Borkido** [comment]
It seems to be fixed for one scope but no scopes still produces an error. I tested both calling `.scope("")` on the builder and omitting the call entirely since i wasnt sure whether the result from the Esi would differ.

**Comment by Celeo** [comment]
Mmm that's unfortunate; I'd hoped that serde would parse that into `serde_json::Value::Null`.

**Comment by Celeo** [comment]
0, 1, and 2 scopes tested in v`0.23.0`; give that a go.

**Comment by Celeo** [comment]
I'm hoping that works. If not, please feel free to reopen. :)
