### ISSUE TITLE
Caching spec result

### ISSUE THREAD

**Issue by saward** [Celeo/rfesi#18]
Hi,

One challenge I have is that I'm storing a bunch of accounts, and then I loop over them, creating an ESI object for each, updating, then discarding.  But it's really slow to call update_spec on each of those each time.

I had thought I could cache the 'spec' value for the life of the program, but the spec value is private so I can't manually specify it.

Do you have any suggestions on how to resolve this?  I wondered about adding a method to allow manual setting of spec (or making it public), or perhaps some other approach with the existing code that I'm not thinking of?

Perhaps I should be creating and storing the ESI object itself as a whole once, and then cloning that each time I need it (and updating the access/refresh/expiration values).  Scopes don't differ, so that might work.

Thanks!

**Comment by Celeo** [comment]
Hi!

Yup, that makes total sense. I've just pushed [a new release](https://github.com/Celeo/rfesi/releases/tag/v0.25.0) that allows for doing this:

```rust
#[tokio::main]
async fn main() {
    let mut esi = EsiBuilder::new()
        .user_agent("...")
        .build()
        .unwrap();

    esi.update_spec().await.unwrap();
    let spec = esi.get_spec();

    let esi2 = EsiBuilder::new()
        .user_agent("...")
        .spec(spec.cloned())
        .build()
        .unwrap();

    println!(
        "{:?}",
        esi2.group_character()
            .get_public_info(91316135)
            .await
            .unwrap()
    );
}
```

Note the new `Esi::get_spec` and `EsiBuilder::spec` functions, which hopefully solves for what you're experiencing. Let me know!

**Comment by saward** [comment]
Looks good, thanks!
