### ISSUE TITLE
Documentation for how to use Groups

### ISSUE THREAD

**Issue by jeanlucthumm** [Celeo/rfesi#2]
I don't really understand how to use the structs in the `groups` module, and I couldn't find any sample code in the documentation. For example, I was trying to get all the market orders in a region so I started by looking at the documentation for `Esi` and found the [`group_market`](https://docs.rs/rfesi/0.8.0/rfesi/prelude/struct.Esi.html#method.group_market) function with the description of "Call endpoints under the "Market" group in ESI.". So far so good. I then saw it returned a `MarketGroup` struct, so I went to see what I can do with that [here](https://docs.rs/rfesi/0.8.0/rfesi/groups/struct.MarketGroup.html). But I couldn't find anything useful in that documentation, like a function to do the actual endpoint querying.

**Comment by Celeo** [comment]
Hi, thanks for your interest!

You've found exactly where the functions _would be_ in the docs - you're spot on. There just haven't been any functions added to [that module](https://github.com/Celeo/rfesi/blob/master/src/groups/market.rs) yet. If there's an endpoint (or endpoints) you want to use, I can add them for you.

**Comment by jeanlucthumm** [comment]
Oh! That makes more sense. I can add the endpoints, I'll send you a PR if that's chill.

I think it might be a good idea to mention this more explicitly in the documentation / readme. I did see your note in the readme about not having implemented all the endpoints, but I didn't realize this would mean empty structs. (Or maybe I'm exceptionally dense, I guess).

**Comment by Celeo** [comment]
> I'll send you a PR if that's chill

Absolutely!

> mention this more explicitly in the documentation / readme

Good call, I'll make that more clear.
