### ISSUE TITLE
Using Esi client without authentication

### ISSUE THREAD

**Issue by jeanlucthumm** [Celeo/rfesi#3]
For the app I'm building, I'm exclusively querying public APIs, and therefore haven't gone through the trouble of setting up an app on EVE. What are your thoughts on supporting this use case? Currently `EsiBuilder` will panic if its missing any of client id, client secret, or callback URL, all of which are unnecessary if only using the public API.

`EsiBuilder` could potentially not panic if it's missing those three values and produce a "public only"  `Esi` struct which panics on any Api call not marked with `RequestType::Public` instead.

**Comment by Celeo** [comment]
Hi, thanks for raising this.

Yeah, that makes sense to me. It should be pretty simple, as there is [already a check for calling an auth'd endpoint without an access token](https://github.com/Celeo/rfesi/blob/5ecd6a14cdfbeb21f90c82bf0bc054a54cb6ed99/src/client.rs#L279).

**Comment by Celeo** [comment]
Added in https://github.com/Celeo/rfesi/commit/3e794d82327b80b47a01f6a4fb7589e61c38ae1f and released in [`v0.9.0`](https://github.com/Celeo/rfesi/releases/tag/v0.9.0).

**Comment by jeanlucthumm** [comment]
Oh rip forgot to mention I was working on a PR haha:

https://github.com/jeanlucthumm/rfesi/commit/da851cfaea3f5c95d5a2e599c4c42a16c1cbf5c6

Oh well!

**Comment by Celeo** [comment]
Oh dang, I'm sorry! Well, if there's anything about what I did that doesn't work or you think could be handled better, I'm happy to still take contributions.

Regardless, thanks for bringing this up!
