### ISSUE TITLE
IndustryGroup::get_character_industry_jobs does not expose include_completed

### ISSUE THREAD

**Issue by jhelwig** [Celeo/rfesi#35]
The `include_completed` parameter on the [character industry jobs ESI endpoint](https://esi.evetech.net/ui/#/Industry/get_characters_character_id_industry_jobs) is not available through the `IndustryGroup::get_character_industry_jobs` interface.

**Comment by Celeo** [comment]
Fixed in release [0.39.0](https://github.com/Celeo/rfesi/releases/tag/v0.39.0). Let me know if it works for you!

**Comment by jhelwig** [comment]
Thanks for the quick update. I ended up going on a couple of other side quests, but I should be able to try it out again soon.

**Comment by jhelwig** [comment]
This looks to be working just fine. Thanks!

**Comment by Celeo** [comment]
Great!
