### ISSUE TITLE
Is the update_spec function working?

### ISSUE THREAD

**Issue by saward** [Celeo/rfesi#40]
I last used this in January, and just tried reloading my app, and now the update spec fails with a timeout.  I tried updating to latest version of this package, and still has the same result.

I can't actually even remember why I was doing this :)

```
                    let mut esi = EsiBuilder::new()
                        .user_agent("some user agent")
                        .scope(SCOPES)
                        .client_id("<hidden>")
                        .client_secret("<hidden>")
                        .callback_url("http://localhost:14413/callback")
                        .build().context("builder failed")?;
                    esi.update_spec().await.context("update spec failed")?;
```

The error I see:

```
thread 'main' panicked at src/app.rs:215:38:
called `Result::unwrap()` on an `Err` value: update spec failed

Caused by:
    0: Error constructing HTTP client
    1: request or response body error: operation timed out
    2: operation timed out
```

Not sure why there would be a timeout, wondering if an underlying EVE url no longer works or is currently having an outage?

**Comment by Celeo** [comment]
Hi!

Hmm, seems to be working for me. Can you share with version of the library you're using? Thanks!

**Comment by saward** [comment]
Tried this version before creating this issue:

```
rfesi = { version = "0.42.0", default-features = false, features = ["validate_jwt"] }
```

I'm not really sure why it's not working, if it's working for you!

**Comment by Celeo** [comment]
Like this: https://gist.github.com/Celeo/86411a3211c7d177285f916d6d4d068f ?

**Comment by saward** [comment]
Well, it looks like my original code works now, without any change.  Must have been a temporary network issue with myself and CCP's servers.  Not sure what went wrong!

**Comment by Celeo** [comment]
How weird! Well, I'm happy it's working now.
