### ISSUE TITLE
Error when trying to authenticate user using .enable_application_authentication(true) with Builder

### ISSUE THREAD

**Issue by rafaga** [Celeo/rfesi#41]
when I execute `let claims_option = self.esi.authenticate(oauth_data.0.as_str(), verifier).await?;` 

rfesi throws a HTTP 400 when running

```
let resp = self
    .client
    .post(&self.token_url)
    .headers(self.get_auth_headers()?)
    .form(&body)
    .send()
    .await?;
```
this is client.rs line 328-334 from rfesi

anmd on Terminal this message appears

`024-04-23 20:50:04.782199-0600 Application[10289:39096] [miscellany] CLIENT ERROR: TUINSRemoteViewController does not override -viewServiceDidTerminateWithError: and thus cannot react to catastrophic errors beyond logging them`

Any ideas what could be? It works when I'm not using `.enable_application_authentication(true)` in Builder

**Comment by Celeo** [comment]
Hey sorry, haven't looked yet but will do so soon.

On Tue, Apr 23, 2024, at 7:59 PM, Rafael wrote:
> 
> 
> when I execute `let claims_option = self.esi.authenticate(oauth_data.0.as_str(), verifier).await?;`
> 
> rfesi throws a HTTP 400 when running
> 
> `let resp = self
>     .client
>     .post(&self.token_url)
>     .headers(self.get_auth_headers()?)
>     .form(&body)
>     .send()
>     .await?;
`

**Comment by Celeo** [comment]
Hmm, very odd. I was able to create a new application on the Eve devs site and do this:

```rust
    let mut esi = rfesi::prelude::EsiBuilder::new()
        .user_agent("github.com/celeo/rfesi")
        .client_id("abc...")
        .callback_url("http://localhost:5000/sso/callback")
        .enable_application_authentication(true)
        .build()
        .unwrap();
    let auth_url = esi.get_authorize_url().unwrap();
    info!("Auth url: {}", auth_url.authorization_url);
    debug!("PKCE: {}", auth_url.pkce_verifier.unwrap());
}
```

then access the URL, grab the code from the URL, and put it in:

```rust
    let mut esi = rfesi::prelude::EsiBuilder::new()
        .user_agent("github.com/celeo/rfesi")
        .client_id("abc...")
        .callback_url("http://localhost:5000/sso/callback")
        .enable_application_authentication(true)
        .build()
        .unwrap();
    let claims = esi
        .authenticate(
            "code_from_url",
            Some("verification_from_before".to_string()),
        )
        .await
        .unwrap();
    dbg!(claims);
```

and got:

```plain
[src/main.rs:27:5] claims = Some(
    TokenClaims {
        aud: [
            "...",
            "EVE Online",
        ],
        azp: "...",
        exp: ...,
        iat: ...,
        iss: "https://login.eveonline.com",
        jti: "...",
        kid: "JWT-Signature-Key",
        name: "Celeo Servasse",
        owner: "abc...",
        region: "world",
        scp: None,
        sub: "CHARACTER:EVE:91316135",
        tenant: "tranquility",
        tier: "live",
    },
)
```

**Comment by rafaga** [comment]
Let me check my code its probably error on my side

**Comment by rafaga** [comment]
I'll close because I haven't so much time to verify this, I'll resume this when I have finished some tasks in my application. fo
