### ISSUE TITLE
Endpoint for Notifications & A few more :)

### ISSUE THREAD

**Issue by turulix** [Celeo/rfesi#45]
Hey! Could you implement [/characters/{character_id}/notifications/](https://esi.evetech.net/ui/#/operations/Character/get_characters_character_id_notifications),[/characters/{character_id}/wallet/transactions/](https://esi.evetech.net/ui/#/operations/Wallet/get_characters_character_id_wallet_transactions) and [/ui/openwindow/marketdetails/](https://esi.evetech.net/ui/#/operations/User%20Interface/post_ui_openwindow_marketdetails) ? :D

Would be awsome if this could be implemented!

Thanks in advance

**Comment by Celeo** [comment]
You betcha!

**Comment by Celeo** [comment]
https://github.com/Celeo/rfesi/releases/tag/v0.45.0 should publish in a few minutes; let me know if those work for you.

**Comment by turulix** [comment]
I believe this has to be an authenticated request aswell
https://github.com/Celeo/rfesi/blob/fdf077ef83ce3682731dd7140826f6df7769396c/src/groups/user_interface.rs#L21-L23

And if the groups are supost to be the same as on the ESI swagger page, the transactions should be part of the wallet

**Comment by Celeo** [comment]
Whoops, typo.

**Comment by Celeo** [comment]
Update deploying https://github.com/Celeo/rfesi/releases/tag/v0.45.1
